### ISSUE TITLE
可否支持firefox？

### ISSUE THREAD

**Issue by xiaozixun** [yuhaofe/Quick-Bookmarks-Menu#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by flyhaozi** [comment]
开发这个扩展的初衷就是因为 Chrome 和 Edge 上没有 Firefox 那种原生的书签菜单，Firefox 的书签菜单已经相当好用了，而且性能比扩展实现要好得多，短期内不考虑上架 Firefox 商店，等扩展功能开发得更完善的时候再说。

**Comment by xiaozixun** [comment]
> 
> 
> 开发这个扩展的初衷就是因为 Chrome 和 Edge 上没有 Firefox 那种原生的书签菜单，Firefox 的书签菜单已经相当好用了，而且性能比扩展实现要好得多，短期内不考虑上架 Firefox 商店，等扩展功能开发得更完善的时候再说。

嗯，好吧。

**Comment by flyhaozi** [comment]
> 嗯，好吧。如果可以的话希望能支持侧栏

是指停靠在网页左右的书签侧栏吗，Chromium 扩展没有侧栏的API，要实现的话就只能插入到网页内容里，体验不会特别好，不过我也会考虑下

**Comment by xiaozixun** [comment]
> 
> 
> > 嗯，好吧。如果可以的话希望能支持侧栏
> 
> 是指停靠在网页左右的书签侧栏吗，Chromium 扩展没有侧栏的API，要实现的话就只能插入到网页内容里，体验不会特别好，不过我也会考虑下

不是的，我是指Firefox的侧栏，chromium系的侧栏我几乎没用过

**Comment by flyhaozi** [comment]
> 不是的，我是指Firefox的侧栏，chromium系的侧栏我几乎没用过

Chromium可以说是没有侧栏，扩展都是插入网页模仿出来的😂

查了下Firefox是有给扩展的sidebar_action的，如果做Firefox版的话我会考虑整下的
